<?php
require __DIR__ . '/../config/database.php';require_admin();
$conversationId=filter_input(INPUT_GET,'conversation_id',FILTER_VALIDATE_INT)?:0;
$targetUser=filter_input(INPUT_GET,'user_id',FILTER_VALIDATE_INT)?:0;
if(!$conversationId&&$targetUser){$q=$pdo->prepare("INSERT INTO conversations(user_id,status) SELECT users.id,'open' FROM users WHERE users.id=? AND users.role='user' ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(conversations.id)");$q->execute([$targetUser]);$conversationId=(int)$pdo->lastInsertId();}
$unread=(int)($_GET['unread']??0);$search=trim((string)($_GET['q']??''));
$pageTitle='Tin nhắn hỗ trợ';require __DIR__.'/../includes/header.php';require __DIR__.'/_nav.php';
?>
<h1 class="h3 mb-3">Trung tâm chat hỗ trợ</h1>
<div class="admin-chat" data-chat-admin data-api="<?= e(app_url('chat/api.php')) ?>" data-csrf="<?= e(csrf_token()) ?>" data-selected="<?= $conversationId ?>">
<aside class="chat-inbox"><form method="get" class="mb-2"><input class="form-control mb-2" name="q" value="<?= e($search) ?>" placeholder="Tìm khách hàng"><label><input type="checkbox" name="unread" value="1" <?= $unread?'checked':'' ?>> Chưa đọc</label><button class="btn btn-sm btn-outline-success ms-2">Lọc</button></form><div data-chat-list></div></aside>
<section class="chat-panel"><header data-chat-heading>Chọn cuộc trò chuyện</header><div class="chat-thread" data-chat-thread aria-live="polite"></div><form class="chat-compose" data-chat-form><label class="chat-image-pick" title="Chọn ảnh" aria-label="Chọn ảnh"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="3.5" y="3.5" width="17" height="17" rx="3" stroke="currentColor" stroke-width="1.8"/><circle cx="8.5" cy="8.5" r="1.6" fill="currentColor"/><path d="m5.5 18 5.2-5.2a1.8 1.8 0 0 1 2.55 0L15 14.5l1.5-1.5a1.7 1.7 0 0 1 2.4 0l1.1 1.1" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg><input type="file" name="image" accept="image/jpeg,image/png,image/webp" hidden data-chat-image></label><span data-chat-preview></span><textarea name="message" rows="2" maxlength="4000" class="form-control" placeholder="Nhập tin nhắn..." aria-label="Nhập tin nhắn..."></textarea><button class="btn btn-success">Gửi</button></form><form method="post" action="<?= e(app_url('chat/api.php')) ?>" data-confirm data-confirm-ajax data-confirm-stay data-confirm-title="Xóa tin nhắn" data-confirm-message="Tin nhắn sẽ bị xóa cho cả Admin và khách hàng." data-confirm-tone="danger" data-confirm-button="Xóa tin nhắn" data-chat-delete-form hidden><?= csrf_field() ?><input type="hidden" name="action" value="delete_message"><input type="hidden" name="conversation_id" value="<?= $conversationId ?>" data-delete-conversation><input type="hidden" name="message_id" value="" data-delete-message-id></form><form method="post" action="<?= e(app_url('chat/admin_action.php')) ?>" data-chat-close class="mt-2"><?= csrf_field() ?><input type="hidden" name="action" value="close"><input type="hidden" name="conversation_id" value="<?= $conversationId ?>"><button type="submit" class="btn btn-sm btn-outline-secondary">Kết thúc cuộc trò chuyện</button></form><div class="small text-danger" data-chat-error></div></section></div>
</section></div><?php require __DIR__.'/../includes/footer.php'; ?>
